version: "3.9"

services:
  db_postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  go_api:
    build:
      context: ./api/
      dockerfile: ./dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - go_api
