FROM golang:alpine AS build

WORKDIR /build

COPY go.mod go.sum ./
COPY *.go ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o ./bin/app

FROM scratch
WORKDIR /app
COPY --from=build /build/bin/app .
CMD ["/app/app"]